// auth0-fe/react-auth0-hello-world/src/portal/Portal.tsx
import { useAuth0 } from "@auth0/auth0-react";
import { Link } from "react-router-dom";
import { useEffect, useState, useRef } from 'react';
import { CumulioDashboardComponent, CumulioDashboard } from "@cumul.io/react-cumulio-dashboard";
import './portal.css';

const appServer = 'APP_SERVER_HERE';
const apiHost = 'API_HOST_HERE';

function Portal() {
  const [dashboardId, setDashboardId] = useState<string | undefined>('');
  const [key, setKey] = useState<string | null>(null);
  const [token, setToken] = useState<string | null>(null);
  const { isAuthenticated, user, logout, getAccessTokenSilently } = useAuth0();
  console.log(user);
  const ref = useRef<CumulioDashboard | null>(null);

  useEffect(() => {
    getAccessTokenSilently().then(token => {
      if (user) {
        window.fetch(`http://localhost:4001`, {
          method: 'POST',
          body: JSON.stringify({
            username: user?.nickname,
            name: user?.name,
            email: user?.email,
            suborganization: user?.nickname
          }),
          headers: {
            'Authorization': 'Bearer ' + token,
            'Content-Type': 'application/json'
          }
        })
        .then(response => response.json())
        .then((data) => {
          setTimeout(() => {
            setKey(data.key);
            setToken(data.token);
            setTimeout(() => {
              ref.current?.getAccessibleDashboards().then(dashboards => {
                console.log(dashboards);
                if (dashboards) {
                  setDashboardId(dashboards[0].id);
                }
              });
            }, 100);
          }, 2000);
  
        });
      }
    });

  }, [user]);


  return isAuthenticated && user ? <div className="position-relative">
    <nav className="navbar navbar-dark" style={{
      'backgroundColor': user['https://cumulio/brand'] === 'Mars Boots' ? '#f06292' : '#d32f2f'
    }}>
      <div className="container">
        <Link className="navbar-brand" to="#">{ user['https://cumulio/brand'] === 'Mars Boots'  ? 'MARS BOOTS' : 'EARTHLY SHOES'}</Link>
        <span className="d-flex navbar-email position-relative">
          <strong>{user?.email}</strong>
          <div className="position-absolute btn btn-dark btn-logout" onClick={() => logout({ returnTo: window.location.origin })}>Logout</div>
        </span>
      </div>

    </nav>
    <div className="container mt-4 position-relative dashboard-loader">
    { key && token ? <CumulioDashboardComponent
      ref={ref}
      dashboardId={dashboardId}
      authKey={key}
      authToken={token}
      appServer={appServer}
      apiHost={apiHost}
      mainColor="pink"
      accentColor="black"
      loaderSpinnerColor="rgb(0, 81, 126)"
      loaderSpinnerBackground="rgb(236 248 255)"
      itemsRendered={(e) => console.log("itemsRendered", e)}
      exported={(e) => console.log("exported", e)}
      load={(e) => console.log("load", e)}
    ></CumulioDashboardComponent> : <div className="spinner-border text-danger loader" role="status">
    <span className="visually-hidden">Loading...</span>
  </div> }
    </div>
    </div> : <div className="spinner-border text-danger loader" role="status">
    <span className="visually-hidden">Loading...</span>
  </div>;
}

export default Portal;

// auth0-fe/angular-auth0-hello-world/src/app/portal/portal.component.ts
import { Component, OnInit, Inject, ViewChild, ElementRef } from '@angular/core';
import { AuthService } from '@auth0/auth0-angular';
import { DOCUMENT } from '@angular/common';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { NgxCumulioDashboardComponent } from '@cumul.io/ngx-cumulio-dashboard';
import { combineLatestWith, forkJoin, take } from 'rxjs';
@Component({
  selector: 'app-portal',
  templateUrl: './portal.component.html',
  styleUrls: ['./portal.component.scss']
})
export class PortalComponent implements OnInit {

  @ViewChild('dashboardInstance') dashboardInstance?: NgxCumulioDashboardComponent;

  dashboardId: string | undefined = undefined;
  appServer='APP_SERVER_HERE';
  apiHost='API_HOST_HERE';
  key?: string;
  token?: string;

  constructor(@Inject(DOCUMENT) public document: Document, public auth: AuthService, private http: HttpClient) {}

  ngOnInit(): void {
    // We can use raw claims to send JWT token instead of cumulio object.
    this.auth.user$.pipe(
      take(1),
      combineLatestWith(this.auth.getAccessTokenSilently())
    )
    .subscribe({ 
      error: (err) => console.log(err),
      next: ([user, token]) => {
        console.log(token, user);
        this.http.post<{
          status: string;
          key?: string;
          token?: string;
        }>(`http://localhost:4001`, {
          username: user?.nickname,
          name: user?.name,
          email: user?.email,
          suborganization: user?.nickname
        }, {
          headers: {
            'Authorization': 'Bearer ' + token,
            'Content-Type': 'application/json'
          }
        })
        .subscribe((data) => {
          console.log(data);
          this.key = data.key;
          this.token = data.token;
          console.log('Fetching accessible dashboards');

          setTimeout(() => {
            // dynamically fetch dashboards and load the first one
            this.dashboardInstance?.getAccessibleDashboards().subscribe(dashboards => {
              this.dashboardId = dashboards[0]?.id;
            });
          }, 100);

        });
      } 
    });
  }

}

<div *ngIf="auth.user$ | async as user else loader" class="position-relative">
  <nav class="navbar navbar-dark" [ngStyle]="{
    'background-color': user['https://cumulio/brand']?.[0] === 'Mars Boots' ? '#f06292' : '#d32f2f'
  }">
    <div class="container">
      <a class="navbar-brand" href="#">{{ user['https://cumulio/brand']?.[0] === 'Mars Boots'  ? 'MARS BOOTS' : 'EARTHLY SHOES'}}</a>
      <span class="d-flex navbar-email position-relative">
        <strong>{{user.email}}</strong>
        <div *ngIf="auth.isAuthenticated$ | async" class="position-absolute btn btn-dark btn-logout" (click)="auth.logout({ returnTo: document.location.origin })">Logout</div>
      </span>
    </div>
  </nav>
  <div class="container mt-4">
    <cumulio-dashboard
      #dashboardInstance
      *ngIf="key && token"
      [dashboardId]="dashboardId"
      [authKey]="key"
      [authToken]="token"
      [appServer]="appServer"
      [apiHost]="apiHost"
    >
    </cumulio-dashboard>
  </div>
</div>
<ng-template #loader>
  <div class="spinner-border text-danger loader" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
</ng-template>
