// auth0-fe/angular-auth0-hello-world/src/app/home/home.component.ts
import { Component, OnInit, Inject } from '@angular/core';
import { AuthService } from '@auth0/auth0-angular';
import { DOCUMENT } from '@angular/common';
import { Router } from '@angular/router';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent {

  showLoader = true;

  constructor(@Inject(DOCUMENT) public document: Document, public auth: AuthService, public router: Router) {
    auth.isAuthenticated$.subscribe(isAuthenticated => {
      this.showLoader = false;
      if (isAuthenticated) {
        router.navigateByUrl('/portal')
      }
    });
  }
}

<div class="container container-whole text-center">
  <div class="spinner-border text-danger loader" role="status" *ngIf="showLoader">
    <span class="visually-hidden">Loading...</span>
  </div>
  <span class="text-center h1-bg inline-block p-2">UNIVERSAL FOOTWEAR</span>
  <div class="row text-center links-container">
    <div class="offset-lg-2 col-12 col-lg-3">
      <div class="row">
        <div class="col-12">
          Lorem ipsum dolor sit amet consectetur adipisicing elit.
          Aut vero cum enim quibusdam quaerat.
          Quos modi temporibus tempora suscipit qui.
          Quis nemo ut labore ex. Quia aspernatur dolores eveniet minima!
        </div>
      </div>
      <a class="btn btn-lg btn-primary btn-purple mt-5" (click)="router.navigateByUrl('/investor')">
        Investor relations
      </a>
    </div>
    <div class="offset-lg-2 col-12 col-lg-3 mt-5 mt-lg-0">
      <div class="row">
        <div class="col-12">
          Lorem ipsum dolor sit amet consectetur adipisicing elit.
          Aut vero cum enim quibusdam quaerat.
          Quos modi temporibus tempora suscipit qui.
          Quis nemo ut labore ex. Quia aspernatur dolores eveniet minima!
        </div>
      </div>
      <a class="btn btn-lg btn-primary btn-purple mt-5" (click)="auth.loginWithRedirect()">
        Brand portal
      </a>
    </div>
  </div>
</div>

// auth0-fe/react-auth0-hello-world/src/home/Home.tsx
import './home.css';
import { useAuth0 } from "@auth0/auth0-react";
import { Link, useNavigate } from 'react-router-dom';
import { useEffect } from 'react';


function Home() {
  const { loginWithRedirect, isAuthenticated, isLoading } = useAuth0();
  const navigate = useNavigate();

  useEffect(() => {
    if (isAuthenticated) {
      navigate('/portal', { replace: true });
    }
  }, [isAuthenticated, navigate]);

  return <div className="container container-whole text-center">
      { isLoading ? <div className="spinner-border text-danger loader" role="status">
        <span className="visually-hidden">Loading...</span>
      </div> : <div></div>}
      <span className="text-center h1-bg inline-block p-2">UNIVERSAL FOOTWEAR</span>
      <div className="row text-center links-container mt-5">
        <div className="offset-lg-2 col-12 col-lg-3">
          <div className="row">
            <div className="col-12">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Aut vero cum enim quibusdam quaerat.
              Quos modi temporibus tempora suscipit qui.
              Quis nemo ut labore ex. Quia aspernatur dolores eveniet minima!
            </div>
          </div>
          <Link to='/investor' className="btn btn-lg btn-primary btn-purple mt-5" >
            Investor relations
          </Link>
      </div>
      <div className="offset-lg-2 col-12 col-lg-3 mt-5 mt-lg-0">
          <div className="row">
            <div className="col-12">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Aut vero cum enim quibusdam quaerat.
              Quos modi temporibus tempora suscipit qui.
              Quis nemo ut labore ex. Quia aspernatur dolores eveniet minima!
            </div>
          </div>
          <div className="btn btn-lg btn-primary btn-purple mt-5" onClick={() => loginWithRedirect()}>
            Brand portal
          </div>
      </div>
      </div>
    </div>;
}

export default Home;
